### ISSUE TITLE
Error displaying Project details

### ISSUE THREAD

**Issue by 963design** [nafiesl/free-pmo#78] opened 2021-09-06 19:05 UTC
![free-pmo-issue](https://user-images.githubusercontent.com/10729609/132254424-86fa4168-4bf3-4ec0-8a48-d042c5e5d68e.png)

Hello i just testing the project and after changing agency details and adding a few customers and a new project, the program shows this error message related to project-stats partial where is unable to show info in the url .../projects/{projectID}

As an extra info Im testing the system using sqlite database.

**Comment by nafiesl** [comment] 2021-09-06 21:23
Hello @963design, thanks for the info, could you inform your PHP version?

**Comment by nafiesl** [comment] 2021-09-26 14:49
Hello @963design sorry for my delayed response. Did you still experience this issue?

I am trying to reproduce the bug on PHP 7.4.15 and SQLite database, but no luck. The project detail page is rendered with no errors. Here is how I reproduce:

1. Try to get a fresh install of the Free PMO project
2. Create an SQLite database on `database/database.sqlite`
3. Update the `.env` file: `DB_CONNECTION=sqlite
4. Remove other env vars: `DB_HOST, DB_DATABASE, DB_USERNAME, DB_PASSWORD`
5. Installation completed (the agency created)
6. Create a new project with a new customer
7. Open the newly created project detail
8. The page rendered properly (with no error)

Screenshot:

The project detail page.

![screen_2021-09-26_003](https://user-images.githubusercontent.com/8721551/134812688-5594ec47-3a3f-4095-b14f-8bc17a1ce402.jpg)

Currently, there are no possible solutions for this issue since I cannot reproduce the bug. Do you have more information that might I missed, @963design?

Thanks

**Comment by nafiesl** [comment] 2022-08-06 07:49
Hello @963design, I am closing this issue, feel free to re-open if you have further questions.

**Closed by nafiesl** 2022-08-06 07:49 UTC
